# Generated by Django 3.2.13 on 2022-09-02 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('operations', '0003_auto_20220825_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetychecklist',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklistorder', to='customers.order'),
        ),
    ]
